version: '3'
services:
  auth:
    image: auth_spring:v0.1
    build:
      ../
    container_name: auth
    ports:
      - '5000:8080'
      # External port: internal port
    depends_on:
      # Awaits the database to initialize properly
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}'
      - 'SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}'

  db:
    image: 'ubuntu/mysql:8.0-21.04_edge'
    container_name: mysql
    restart: always
    ports:
      - '3308:3308'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_TCP_PORT=${MYSQL_TCP_PORT}'
    cap_add:
      - SYS_NICE
    volumes:
      - './mysql/_data:/var/lib/mysql'
